name: Get latest data for backtesting.
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Updating Status.'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch release version
        run: |
           rm -rf user_data/data
           git submodule sync
           git submodule update --init --remote --recursive
      - name: Commit latest data version
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add .
          git commit -am "Update Data Version."
          git push